services:
  melissa.webserver:
    image: melissa.web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melissa_webserver
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - AllUNeedApiUrl=https://alluneed.com.br/api/
      - AllUNeedApiKey=
      - OLLAMA_URL=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    container_name: melissa_ollama
    ports:
      - "11434"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [ gpu ]
    
networks:
    default:
        driver: bridge

volumes:
  melissa_data:
    driver: local
